### ISSUE TITLE
Plan for releases

### ISSUE THREAD

**Issue by dornera** [MITLibraries/mitlib-terraform#42]
Come up with a method for deploying releases when we update a module and not use master branch (bad practice)

* Dependabot may help with this
* For now, make sure to run `terraform get --update` so it pulls the latest master

**Comment by JPrevost** [comment]
I ran into this locally. I was seeing changes to apply when I ran `terraform plan` on the `app/DIP` but Andy was not. Resolving this seems worth the effort as it seems easy to have our deployed infra drift from our terraform configs.

**Comment by vab** [comment]
Stale issue. Became part of a different larger discussion.
